### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by anzhuojinjie** [sunfusheng/MarqueeView#79]
数据是一个beanlist，我这是了   bean的name作为显示内容，当点击的时候怎么获取position

**Comment by anzhuojinjie** [comment]
数据是一个beanlist，我这是了 bean的name作为显示内容，当点击的时候怎么获取bean的id

**Comment by sunfusheng** [comment]
试试 MarqueeView V1.4.1
  // 设置自定义的Model数据类型
  public class CustomModel implements IMarqueeItem {
        @Override
        public CharSequence marqueeMessage() {
            return "...";
        }
    }

    List<CustomModel> messages = new ArrayList<>();
    marqueeView.startWithList(messages);
